h=fs.open("locust-installer.lua","w")
r=http.get("https://raw.githubusercontent.com/Arivias/cc-lua/master/locust/installer.lua")
h.write(r.readAll())
r.close()
h.close()
shell.run("locust-installer.lua")